In [124]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import Imputer
from sklearn.metrics import accuracy_score
from xgboost import XGBRegressor

from subprocess import check_output
#from Preprocessing.reducer import *
from IPython.display import display
pd.options.display.max_columns=None

In [150]:
df_2017 = pd.read_csv('./data_2017.csv')
df_2018 = pd.read_csv('./data_2018.csv')

In [151]:
# This statement filters 2017 dataframe on columns of 2018 dataset
df_2017 = df_2017.filter(items = df_2018.columns)

In [167]:
y = df_2017.block_Num
X = df_2017.drop(['block_Num'], axis=1).select_dtypes(exclude=['object'])
y_2018 = df_2018.block_Num
X_2018 = df_2018.drop(['block_Num'], axis=1).select_dtypes(exclude=['object'])

In [168]:
train_X, test_X, train_y, test_y = train_test_split(X, y, test_size=0.25)

In [181]:
# This Imputer uses the default strategy as mean
my_imputer = Imputer()
train_X = my_imputer.fit_transform(train_X)
test_X = my_imputer.transform(test_X)
X_2018 = my_imputer.fit_transform(X_2018)

In [182]:
type(X_2018)

numpy.ndarray

In [184]:
# y ndarray must be transformed from object to int64
# otherwise, DMatrix in XGBoost is not able to be created

from sklearn import preprocessing
encoder = preprocessing.LabelEncoder()
train_y = encoder.fit_transform(train_y)
test_y = encoder.fit_transform(test_y)
y_2018 = encoder.fit_transform(y_2018)

In [171]:
print(np.unique(train_y, return_counts=True))
print(np.unique(test_y, return_counts=True))

(array([0, 1, 2, 3, 4]), array([  2843, 140686,   4364,  10645,   5074]))
(array([0, 1, 2, 3, 4]), array([  951, 46830,  1478,  3568,  1711]))


In [125]:
my_model = XGBRegressor()
my_model.fit(train_X, train_y, verbose=False)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
       n_jobs=1, nthread=None, objective='reg:linear', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=1)

In [126]:
predictions = my_model.predict(test_X)

In [127]:
from sklearn.metrics import mean_absolute_error
print("Mean Absolute Error : " + str(mean_absolute_error(predictions, test_y)))

Mean Absolute Error : 3.43237070453e-05


In [128]:
np.unique(predictions.round(), return_counts=True)

(array([ 0.,  1.,  2.,  3.,  4.], dtype=float32),
 array([  879, 46912,  1443,  3626,  1678]))

In [129]:
accuracy_score(test_y, predictions.round(), normalize=True)

1.0

In [186]:
accuracy_score(pred.round(), y_2018, normalize=True)

0.00011638733705772812

In [143]:
test_X_2018 = df_2018.drop(['block_Num'], axis = 1).select_dtypes(exclude='object')

In [183]:
pred = my_model.predict(X_2018)

In [185]:
accuracy_score(pred.round(), y_2018, normalize=True)

0.00011638733705772812